import React from 'react'
export const metadata = {
  title: 'GRANT MOLLY | КАТАЛОГ',
  description: 'Generated by Next.js'
}

const CategoryPage = () => {
  return (
    <section className='pt-[150px] text-red-600'>
      <div className='container mx-auto'>
        CategoryPage
        <p className='text-blue-400'>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Et aliquid
          voluptate id odio ipsa magnam, voluptas quaerat sit quod est corrupti
          in accusantium deserunt error, dolor nisi unde optio facere
          consequatur nobis dolore nihil labore doloremque! Alias deleniti
          aliquid dolorem porro ullam, saepe maxime? Deleniti in cupiditate
          consequuntur officiis velit, minima reprehenderit quos distinctio
          veniam facilis voluptate fuga, illo quaerat tempora delectus ea
          explicabo sit, omnis provident. Veritatis at cum repudiandae error
          dolores veniam odio ut quibusdam. Ipsam impedit fugit, consequuntur
          dolores illo id in corrupti magnam velit, repellendus eaque modi
          voluptate fugiat suscipit dolorum corporis ducimus nisi molestias, eos
          eius. Minus atque laudantium commodi rem officiis incidunt totam.
          Totam harum asperiores iure fuga vel repellat modi, odio dolorum ipsum
          dolorem, reprehenderit culpa repudiandae nemo suscipit error, ullam
          doloribus aperiam maxime molestias doloremque facilis ut facere?
          Nesciunt architecto dolores ad, ipsa voluptatum, odit doloribus ex
          obcaecati recusandae aliquid, harum a magnam quae porro fuga aperiam
          impedit iure cupiditate! Ipsum sunt ratione saepe iusto velit sint
          deleniti possimus, vero quod sequi cum nemo, molestiae sit, explicabo
          qui aliquam ex ipsa corporis perferendis earum aspernatur. Nesciunt,
          dolorum dolores, fuga consectetur quis tempore quas explicabo,
          voluptatem adipisci deserunt rem! Porro, officia eligendi. Porro?
        </p>
      </div>
    </section>
  )
}

export default CategoryPage
