import './globals.css'
import Navbar from "../components/navbar/Navbar"
import Footer from "../components/footer/Footer"

export const metadata = {
  title: 'GRANT MOLLY',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <Navbar />
        <div className='min-h-[900px]'>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
