import React from 'react'
export const metadata = {
  title: 'Single Product',
  description: 'Generated by Next.js'
}

const SingleProductPage = ({ params: { id } }) => {
  return (
    <section className='pt-[200px]'>
      <div className="container mx-auto">
      SingleProductPage {id}
      </div>
    </section>
  )
}

export default SingleProductPage
